import type { NextPage } from "next";
import Head from "next/head";
import FavoriteSharpIcon from '@mui/icons-material/FavoriteSharp';
import styles from "../styles/Home.module.css";
import { Avatar, Box, Button, Card, IconButton, InputBase, TextField, Typography } from "@mui/material";
import Image from "next/image";
import SentimentVerySatisfiedTwoToneIcon from '@mui/icons-material/SentimentVerySatisfiedTwoTone';
import React from "react";
import LinearBuffer from "./components/linera";
import { useRouter } from "next/router";
import { fontSize } from "@mui/system";
const Hola: NextPage = () => {
  const [name, setName] = React.useState("")
  const router = useRouter()
  const [pending, setPending] = React.useState(false)
  React.useEffect(() => {
    const timeout = setTimeout(() => {
      setPending(true);
    }, 1000);

    return () => clearTimeout(timeout);
  }, []);
  const handleGetName = () => {
    localStorage.setItem("name", name as string)
    setPending(false);
    const timeout = setTimeout(() => {
      router.push("/hola")
    }, 3000);
  }
  const img = "https://scontent.fdad3-4.fna.fbcdn.net/v/t39.30808-6/354966565_1265000941076638_1353986573356368663_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=aCI9g6i6tesAX8eipbI&_nc_ht=scontent.fdad3-4.fna&oh=00_AfDN0wNBrgDreh_oDPspYgtK7TmS3uwwFJtci3hfgKwd4A&oe=64A675E8"
  return (
    <div className={styles.container}>
      <Head>
        <title>Vmax Martis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;1,400;1,500&family=Raleway&display=swap" rel="stylesheet" />
      </Head>

      <Box
        sx={{
          backgroundImage: `linear-gradient(121deg, rgba(30,11,70,1) 0%, rgba(1,9,10,1) 100%)`, zIndex: 0
        }}
        className={styles.main}
      >
        <Box
          className={styles.imgaa}
          sx={{
            width: '100vw',
            height: '100vh',
            minHeight: "500px", backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >  {pending ?
          <Box display="flex" flexDirection="column" justifyContent={"center"} alignItems="center" alignContent={"center"}>
            <Box component={"img"} src={img} sx={{
              width: "200px", height: "200px", backgroundSize: "cover",
              backgroundPosition: "center", borderRadius: "100px"
            }} />
            <Typography variant="subtitle2" sx={{ color: "white", fontSize: 20, fontWeight: 700, marginTop: 1 }}>Let’s celebrate</Typography>
            <Typography variant="subtitle2" sx={{ color: "white", fontSize: 40, fontWeight: 500 }}>{localStorage.getItem("name")}</Typography>
            <Typography variant="subtitle2" sx={{ color: "white", fontSize: 18, fontWeight: 100 }}>Dress code</Typography>
            <Box display="flex" alignItems={"center"} justifyContent={"space-between"} padding={1} sx={{width: "80%", minWidth:"150px"}}>
              <Typography variant="subtitle2" sx={{ color: "black", fontSize: 20, fontWeight: 700, backgroundColor:"white" , paddingY: 0.5, paddingX: 1, borderRadius: 5 }}>Black </Typography>
              <Typography variant="subtitle2" sx={{ color: "white", fontSize: 12, fontWeight: 300 }}> and </Typography>
              <Typography variant="subtitle2" sx={{ color: "white", fontSize: 20, fontWeight: 700 , backgroundColor:"black"}}>White </Typography>
            </Box>
          </Box>
          :
          <Box sx={{
            width: "auto", height: "auto", minWidth: "36%", bgcolor: "#FFF", marginTop: 5, borderRadius: "4px",
            backgroundColor: "#cadee854", display: "flex", flexDirection: "column",

          }}>
            <LinearBuffer />
          </Box>}

        </Box>
        {/* <h1 className={styles.title}>
          Welcome to <a>Next.js!</a>
        </h1> */}

      </Box>
    </div>
  );
};

export default Hola;
