import type { NextPage } from "next";
import Head from "next/head";
import FavoriteSharpIcon from '@mui/icons-material/FavoriteSharp';
import styles from "../styles/Home.module.css";
import { Avatar, Box, Button, Card, IconButton, InputBase, TextField, Typography } from "@mui/material";
import Image from "next/image";
import SentimentVerySatisfiedTwoToneIcon from '@mui/icons-material/SentimentVerySatisfiedTwoTone';
import React from "react";
import LinearBuffer from "./components/linera";
import { useRouter } from "next/router";
const Home: NextPage = () => {
   const [name, setName] = React.useState("")
   const router = useRouter()
   const [pending, setPending] = React.useState(false)
   React.useEffect(() => {
      const timeout = setTimeout(() => {
         setPending(true);
      }, 3000);

      return () => clearTimeout(timeout);
   }, []);
   const handleGetName = () => {
      localStorage.setItem("name", name as string)
      setPending(false);
      const timeout = setTimeout(() => {
         router.push("/hola")
      }, 3000);
   }
   const img =
      "https://scontent.fdad3-4.fna.fbcdn.net/v/t39.30808-6/354966565_1265000941076638_1353986573356368663_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=aCI9g6i6tesAX8eipbI&_nc_ht=scontent.fdad3-4.fna&oh=00_AfDN0wNBrgDreh_oDPspYgtK7TmS3uwwFJtci3hfgKwd4A&oe=64A675E8"

   return (
      <div className={styles.container}>
         <Head>
            <title>Vmax Martis</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
               href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;1,400;1,500&family=Raleway&display=swap" rel="stylesheet" />
         </Head>

         <Box
            sx={{
               backgroundImage: `linear-gradient(121deg, rgba(30,11,70,1) 0%, rgba(1,9,10,1) 100%)`, zIndex: 0
            }}
            className={styles.main}
         >
            <Box
               className={styles.imgss}
               sx={{
                  width: '100vw',
                  height: '100vh',
                  minHeight: "500px", backgroundSize: "cover",
                  backgroundPosition: "center",
               }}
            >
               <Box sx={{
                  width: "auto", height: "auto", minWidth: "36%", bgcolor: "#FFF", marginTop: 5, borderRadius: "4px",
                  backgroundColor: "#cadee854", display: "flex", flexDirection: "column",

               }}>
                  {pending ? <><Box bgcolor="transparent" display={"flex"} sx={{ justifyContent: "space-between" }}>
                     <Typography variant="h5" fontWeight={700} fontFamily={"monospace"} sx={{ color: "white", padding: 1 }} >Join in Party</Typography>
                     <Box sx={{
                        position: "relative", top: -20, left: 20,
                        width: "50px", height: "50px", borderRadius: 50, backgroundColor: "#FFF",
                        opacity: "63%",
                        display: "flex", alignItems: "center", justifyContent: "center", zIndex: 55
                     }}>
                        <FavoriteSharpIcon sx={{ fontSize: 30, color: "red", zIndex: 500 }} />
                     </Box>
                  </Box>
                     <Box display="flex" flexDirection={"column"} p={2}
                     >
                        <TextField
                           sx={{
                              fontSize: "50px",
                              fontWeight: "bold",
                              color: "#FFF"
                           }}
                           id="input-with-icon-textfield"
                           label="What your name ?"
                           placeholder="Tên của bạn . . ."
                           variant="standard"
                           onChange={(event: any) => setName(event.target.value)}
                        />
                        {name.trim() !== "" && <Button onClick={handleGetName} sx={{ fontSize: "15px", marginTop: 1 }} endIcon={<SentimentVerySatisfiedTwoToneIcon fontSize="large" />}>Okeee</Button>
                        }
                     </Box></> : <LinearBuffer />}
               </Box>
            </Box>
            {/* <h1 className={styles.title}>
          Welcome to <a>Next.js!</a>
        </h1> */}

         </Box>
      </div>
   );
};

export default Home;
